### ISSUE TITLE
Improve GraphQL Schema

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai#1286]
### Main idea

By providing an improved GraphQL schema, faster frontend development can be achieved. It should supports the [Relay Specification](https://relay.dev/docs/guides/graphql-server-specification/) by default, ensuring proper operation in a client environment using React and Relay. The following subtasks exist, with higher priority tasks listed at the top:

```[tasklist]
### Tasks
- [ ] Mutations can return all of the objects and fields that were modified.
- [ ] Support the Node interface and query (global ID). ([graphene](https://docs.graphene-python.org/en/latest/relay/nodes/))
- [ ] Support Connection: edge, cursor, and pageInfo. ([graphene](https://docs.graphene-python.org/en/latest/relay/connection/))
- [ ] Define how to describe the filter and ordering using Type. 
- [ ] Support nested mutations.
- [ ] Support nested queries.
``` 

### Example of the schema:
```graphql
input CustomerWhereInput {
  author: UserRelationWhereInput
  createdAt: DateWhereInput
  description: StringWhereInput
  id: IdWhereInput
  OR: [CustomerWhereInput!]
  AND: [CustomerWhereInput!]
  NOR: [CustomerWhereInput!]
}

input StringWhereInput {
  equalTo: String
  notEqualTo: String
  lessThan: String
  lessThanOrEqualTo: String
  greaterThan: String
  greaterThanOrEqualTo: String
  in: [String]
  notIn: [String]
  exists: Boolean
  matchesRegex: String
  options: String
  text: TextInput
  inQueryKey: SelectInput
  notInQueryKey: SelectInput
}

enum CustomerOrder {
  ACL_ASC
  ACL_DESC
  author_ASC
  author_DESC
  createdAt_ASC
  createdAt_DESC
  description_ASC
  description_DESC
  name_ASC
  name_DESC
  objectId_ASC
  objectId_DESC
  updatedAt_ASC
  updatedAt_DESC
  id_ASC
  id_DESC
}

customers(
    "These are the conditions that the objects need to match in order to be found."
    where: CustomerWhereInput,
    "The fields to be used when sorting the data fetched."
    order: [CustomerOrder!],
    "This is the number of objects that must be skipped to return."
    skip: Int,
    "Returns the items in the list that come after the specified cursor."
    after: String,
    "Returns the first n items from the list."
    first: Int,
    "Returns the items in the list that come before the specified cursor."
    before: String,
    "Returns the last n items from the list."
    last: Int,
    "The read options for the query to be executed."
    options: ReadOptionsInput
  ): CustomerConnection!

type CustomerConnection {
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "A list of edges."
  edges: [CustomerEdge]
  "This is the total matched objecs count that is returned when the count flag is set."
  count: Int!
}

type Query { 
  node(
    "The ID of an object"
    id: ID!
  ): Node
  
  customers(
    "These are the conditions that the objects need to match in order to be found."
    where: CustomerWhereInput,
    "The fields to be used when sorting the data fetched."
    order: [CustomerOrder!],
    "This is the number of objects that must be skipped to return."
    skip: Int,
    "Returns the items in the list that come after the specified cursor."
    after: String,
    "Returns the first n items from the list."
    first: Int,
    "Returns the items in the list that come before the specified cursor."
    before: String,
    "Returns the last n items from the list."
    last: Int,
    "The read options for the query to be executed."
    options: ReadOptionsInput
  ): CustomerConnection!
}
# ...
```
