### ISSUE TITLE
The get/set API for quota configs per quota scope

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1353]
Let's add a simple GraphQL query and mutation to get/set the quota configs and usage for individual quota scopes on a storage host, by invoking the storage-proxy's manager-facing APIs.

```[tasklist]
### Tasks
- [ ] `query QuotaConfig(storage_host_name, quota_scope_id) -> { quota_config { hard_limit_bytes } quota_usage { usage_bytes usage_count } }` (potential responses: configured quota config, quota scope not created yet)
- [ ] `mutation SetQuotaConfig(storage_host_name, quota_scope_id, { hard_limit_bytes })` (potential responses: ok, quota-not-supported, failure, invalid-input, etc.)
- [ ] Enhance the error handling when vfolder upload fails in the middle because `write()` fails (at least we should warn the user with "please check the remaining quota" or ask whether to "delete the incomplete file")
```

If the client is a non-superadmin, the query handler must accept only the quota scope ID from the requesting user's UUID or the project UUIDs that the user has access to.
The mutation should be allowed to superadmin or domain-admins only.

Q. Do we need to add `query QuotaScopeList(storage_host_name)` as a paginated list (for admin-oriented storage-centric page)?
