### ISSUE TITLE
Hide sensitive fields in the config APIs

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1626]
Let's hide sensitive fields like passwords in the config APIs and GraphQL introspection queries.

Note that frontends should not treat the placeholder values sent by the server as a new user input.
```[tasklist]
### Tasks
- [ ] https://github.com/lablup/backend.ai/pull/1627
- [ ] https://github.com/lablup/backend.ai/pull/1632
- [ ] Filter sensitive fields in the `/config/get` manager API
- [ ] Deprecate `/config/get` and `/config/set` manager APIs completely
```
