### ISSUE TITLE
Upgrade to SQLAlchemy v2.0

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#1812]
SQLAlchemy v1.4 is a bridge release to migrate v2.0 with introduction of asyncio-native ORM.
It's been almost one year since the first release of v2.0 and I think it should have less hassles of the early versions.
Our codebase already follows the most of best practices for migration to v2.0.

Let's migrate to v2.0 in favor of better type annotation support.
```[tasklist]
### Tasks
- [ ] [Apply `__allow_unmapped__ = True` to explicitly typed ORM models](https://docs.sqlalchemy.org/en/20/changelog/migration_20.html#migration-to-2-0-step-six-add-allow-unmapped-to-explicitly-typed-orm-models)
- [ ] Replace all `select([])` patterns to `select()` patterns
- [ ] In query results, replace codes that get the field value by key-name with codes that get the field value by field-name. (from `row["name"]` to `row.name`)
```

**Comment by achimnol** [comment]
Let's revisit this issue.

**Comment by Yaminyam** [comment]
I will also join in on this issue.
