### ISSUE TITLE
Per-project custom images 

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#1906]
### Main idea

- [ ] Rebase container registry config storage to relational database
- [ ] Define many-to-many table to represent relations between user scope (project or individual user) and container registry
- [ ] Programmatic image spec validation & kernel image verification tool
- [ ] Commit running session and push image to dedicated registry
- [ ] Create management API for harbor projects dedicated to each user/project
- [ ] Cache interface to store frequently accessed I/O bound data

**Comment by kyujin-cho** [comment]
cc @achimnol
