### ISSUE TITLE
Project-level sharing of compute sessions

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#2346]
Just like project-owned vfolders, there is a need to share compute sessions with project members.

### Phase 1: Session visibility
* [ ] Add a project option to enable project-wise session sharing.
* [ ] When querying sessions (`ComputeSession` GraphQL APIs), accept an explicit project argument and return the sessions created by other members of the project if the sharing option is on.
* [ ] Update the WebUI to disable controls of sessions owned by other project members.

### Phase 2: Collaboration
* [ ] Add a session creation option to enable app sharing with other users.
* [ ] Allow opening the same app of the same session when the project-level session sharing is on.

### Phase 3: RBAC Integration
* [ ] Define project-level roles to allow control the sessions owned by other project members.
