### ISSUE TITLE
Support auto scaling on Model Service

### ISSUE THREAD

**Issue by kyujin-cho** [lablup/backend.ai#2659]
### Main idea

Support for auto scaling is crucial when serving production-grade model service APIs. We can think of supporting the feature by two approaches: Metric-based and Schedule-based.

```Java
### Tasks
- [ ] Show session metric from model service status page
- [ ] implement Metric-based auto scaling (see the subissues)
- [ ] implement Schedule-based auto scaling
```

JIRA Issue: BA-96
