### ISSUE TITLE
Define GraphQL Relay based schema

### ISSUE THREAD

**Issue by fregataa** [lablup/backend.ai#3068]
```Java
### TODO
- [ ] User node
- [ ] Project node
- [ ] Domain node
- [ ] Compute session node
- [ ] Compute kernel node
- [ ] Virtual folder node
- [ ] Agent node
- [ ] Scaling group (resource group) node
- [ ] Storage proxy node
```

JIRA Issue: BA-58
