### ISSUE TITLE
Templated service ports

### ISSUE THREAD

**Issue by achimnol** [lablup/backend.ai#54]
Let's add some customizability to the service ports.
When starting a service, let's allow passing of predefined set of additional arguments.

For security reasons, we need to restrict changing the service port number and executing unexpected arbitrary commands.

**Phase 1**
* [x] Design a simple template format to be stored in kernel images (YAML or JSON)
  - The krunner (agent's `src/ai/backend/kernel`) renders this template.
  - In my thought:
    - The template should consist of strings that optionally contains Python's `str.format`-style string formats, like `"{ports[0]}"`, `"{ports[1]}"`, and so on. Pass the required variables as keyword arguments to `.format_map()` method. Note that `format_map()` allows use of custom mapping classes directly — e.g., `defaultdict` could be used to fill out undefined keys without errors.
    - DO NOT USE `eval()`, `exec()`, or `compile()` that allows arbitrary Python code execution.
    - Better ideas are welcome!
  - Input variables of template:
    - The (in-container) port numbers to be used by the service as `ports`
    - maybe others?
  - Output of template:
    - command-line arguments as a list of strings
    - environment variables as a map of string key-value pairs
* [x] Rewrite existing case-by-case service startup implementations in the agent's `src/ai/backend/kernel/base.py` and other language-specific krunners using the template format, and update kernel images to use it.

**Phase 2**
* [x] Extend the template format to specify white-listed customizable arguments and environment variables.
* [x] Add a new parameter to the manager's stream proxy API so that users can provide additional arguments to the service port's command arguments and environment variables.
